import {
	Banner1,
	Banner2,
	Banner3,
	News1,
	News2,
	News3,
	Product101,
	Product102,
	Product103,
	Product104,
	Product11,
	Product111,
	Product112,
	Product113,
	Product114,
	Product12,
	Product121,
	Product122,
	Product123,
	Product124,
	Product13,
	Product14,
	Product21,
	Product22,
	Product23,
	Product24,
	Product31,
	Product32,
	Product33,
	Product34,
	Product41,
	Product42,
	Product43,
	Product44,
	Product51,
	Product52,
	Product53,
	Product54,
	Product61,
	Product62,
	Product63,
	Product64,
	Product71,
	Product72,
	Product73,
	Product74,
	Product81,
	Product82,
	Product83,
	Product84,
	Product91,
	Product92,
	Product93,
	Product94,
} from "./helper";

const latestNewsItems = [
	{
		id: 1,
		imgSrc: News1,
		date: "25th Apr 2023",
		category: "COLLECTION",
		title: "Products That Shape Fashion",
		description:
			"Donec rhoncus quis diam sit amet faucibus. Vivamus pellentesque, sem sed convallis ultricies, ante eros",
	},
	{
		id: 2,
		imgSrc: News2,
		date: "25th Apr 2023",
		category: "FASHION",
		title: "New Finds From Tuckernuck",
		description:
			"Donec rhoncus quis diam sit amet faucibus. Vivamus pellentesque, sem sed convallis ultricies, ante eros",
	},
	{
		id: 3,
		imgSrc: News3,
		date: "25th Apr 2023",
		category: "CLOTHING",
		title: "Sunset Sets From Saks",
		description:
			"Donec rhoncus quis diam sit amet faucibus. Vivamus pellentesque, sem sed convallis ultricies, ante eros",
	},
];

export const productItems = [
	{
		id: "fp1",
		review: 2,
		quantity: 1,
		price: 29.5,
		discount: 15,
		priceCrossed: 37.5,
		imgSrc1: Product11,
		imgSrc2: Product12,
		imgSrc3: Product13,
		imgSrc4: Product14,
		title: "Short Nylon-Effect Puffer Jacket",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp2",
		review: 4,
		quantity: 1,
		price: 29.9,
		discount: 22,
		priceCrossed: "",
		imgSrc1: Product21,
		imgSrc2: Product22,
		imgSrc3: Product23,
		imgSrc4: Product24,
		title: "Pouch Pocket Hoodie Orange",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp3",
		review: 1,
		quantity: 1,
		price: 18.9,
		discount: 15,
		priceCrossed: 24.5,
		imgSrc1: Product31,
		imgSrc2: Product32,
		imgSrc3: Product33,
		imgSrc4: Product34,
		title: "Blue Starter Logo T-shirt",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp4",
		review: 3,
		quantity: 1,
		price: 24.7,
		discount: 15,
		priceCrossed: 35.3,
		imgSrc1: Product41,
		imgSrc2: Product42,
		imgSrc3: Product43,
		imgSrc4: Product44,
		title: "Long Sleeve Sweatshirt Dress",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp5",
		review: 5,
		quantity: 1,
		price: 21.7,
		discount: 40,
		priceCrossed: 25.8,
		imgSrc1: Product51,
		imgSrc2: Product52,
		imgSrc3: Product53,
		imgSrc4: Product54,
		title: "Long Sleeve Graphic T-shirt",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp6",
		review: 2,
		quantity: 1,
		price: 15.7,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product61,
		imgSrc2: Product62,
		imgSrc3: Product63,
		imgSrc4: Product64,
		title: "Lightweight Zipped Bomber Jacket",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp7",
		review: 2,
		quantity: 1,
		price: 22.7,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product71,
		imgSrc2: Product72,
		imgSrc3: Product73,
		imgSrc4: Product74,
		title: "Basic Colored Sweatpants With Elastic Hems",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp8",
		review: 2,
		quantity: 1,
		price: 15.7,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product81,
		imgSrc2: Product82,
		imgSrc3: Product83,
		imgSrc4: Product84,
		title: "Basic High-Neck Puff Jacket",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp9",
		review: 1,
		quantity: 1,
		price: 12.7,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product91,
		imgSrc2: Product92,
		imgSrc3: Product93,
		imgSrc4: Product94,
		title: "Basic Relax Fit Leggings",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp10",
		review: 2,
		quantity: 1,
		price: 14.2,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product101,
		imgSrc2: Product102,
		imgSrc3: Product103,
		imgSrc4: Product104,
		title: "Check Overshirt With Pocket Detail",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp11",
		review: 5,
		quantity: 1,
		price: 19.5,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product111,
		imgSrc2: Product112,
		imgSrc3: Product113,
		imgSrc4: Product114,
		title: "Rose Printed Hoodie",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
	{
		id: "fp12",
		review: 4,
		quantity: 1,
		price: 18.9,
		discount: 12,
		priceCrossed: 185.8,
		imgSrc1: Product121,
		imgSrc2: Product122,
		imgSrc3: Product123,
		imgSrc4: Product124,
		title: "World Wide Cup Print T-Shirt",
		description:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, ratione doloribus molestias dignissimos tempore laudantium autem quasi odit ab molestiae?",
	},
];

export const footerListItems = [
	{
		id: "f1",
		link: "#!",
		heading: "Information",
		item1: "About Us",
		item2: "Privacy Policy",
		item3: "Returns Policy",
		item4: "Shipping Policy",
		item5: "Dropshipping",
	},
	{
		id: "f2",
		link: "#!",
		heading: "Account",
		item1: "Dashboard",
		item2: "My Orders",
		item3: "My Wishlist",
		item4: "Account details",
		item5: "Track My Orders",
	},
	{
		id: "f3",
		link: "#!",
		heading: "Shop",
		item1: "Affiliate",
		item2: "Bestsellers",
		item3: "Discount",
		item4: "Latest Products",
		item5: "Sale Products",
	},
	{
		id: "f4",
		link: "#!",
		heading: "Categories",
		item1: "Women",
		item2: "Men",
		item3: "Bags",
		item4: "Outerwear",
		item5: "Shoes",
	},
];

export const bannerContents = [
	{
		id: "b1",
		imgSrc: Banner1,
		btnText: "Shop Collection",
		subtitle: "WINTER 2022 COLLECTION",
		title: "Making someone feel pretty is an art",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
	},
	{
		id: "b2",
		imgSrc: Banner2,
		btnText: "Shop Collection",
		subtitle: "WINTER 2022 COLLECTION",
		title: "Valentin Paul Essential Collection",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
	},
	{
		id: "b3",
		imgSrc: Banner3,
		btnText: "Shop Collection",
		subtitle: "WINTER 2022 COLLECTION",
		title: "Valentin David Essential Collection",
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
	},
];

export const dropdownItems = [
	{
		id: 1,
		title: "Shop Lists",
		listItem1: "Shop Default",
		listItem2: "Shop Right Sidebar",
		listItem3: "Shop Wide",
		listItem4: "Filters Area",
		listItem5: "List Left Sidebar",
		listItem6: "Load More Button",
		listItem7: "Infinite Scrolling",
	},
	{
		id: 2,
		title: "Product Details",
		listItem1: "Product Variable",
		listItem2: "Product Default",
		listItem3: "Product Grouped",
		listItem4: "Product External",
		listItem5: "Product Downloadable",
		listItem6: "Produt With Video",
		listItem7: "Without Recently Viewed",
	},
	{
		id: 3,
		title: "Shop Pages",
		listItem1: "Cart",
		listItem2: "Checkout",
		listItem3: "My account",
		listItem4: "Wishlist",
		listItem5: "Order Tracking",
		listItem6: "Best Selling Products",
		listItem7: "Terms and Conditions",
	},
	{
		id: 4,
		title: "Shop Layout",
		listItem1: "Two Columns",
		listItem2: "Three Columns",
		listItem3: "Three Columns",
		listItem4: "Four Columns",
		listItem5: "Four Columns",
		listItem6: "Four Columns",
		listItem7: "Four Columns",
	},
];

export default latestNewsItems;
